development:
  adapter: postgresql
  database: check_in_development
  host: localhost

test:
  adapter: postgresql
  database: check_in_test
  host: localhost

production:
  adapter: postgresql
  database: check_in_production
  host: localhost
